import { createFileRoute, useServerFn } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useRef, useState } from "react";
import {
  Compass,
  HeartHandshake,
  ShieldCheck,
  Sparkles,
  Copy,
  Download,
  RefreshCw,
  Loader2,
  ChevronRight,
  BookOpen,
  Users,
  Lightbulb,
} from "lucide-react";
import { toast, Toaster } from "sonner";

import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { generateCampaign, type CampaignResult } from "@/lib/campaign.functions";

export const Route = createFileRoute("/")({
  component: BeaconPage,
});

const AUDIENCES = [
  "Students",
  "Parents",
  "Teachers",
  "Community Members",
  "Event Attendees",
  "Healthcare Professionals",
];
const FOCUSES = [
  "Prevention",
  "Recognizing Warning Signs",
  "Survivor Support",
  "Reporting Resources",
  "Community Awareness",
];
const FORMATS = [
  "Instagram Post",
  "Facebook Post",
  "LinkedIn Post",
  "Poster",
  "Flyer",
  "Awareness Speech",
  "Event Announcement",
];
const TONES = ["Informative", "Encouraging", "Professional", "Community-focused"];

function BeaconPage() {
  const generatorRef = useRef<HTMLDivElement>(null);
  const resultRef = useRef<HTMLDivElement>(null);

  const [audience, setAudience] = useState("Students");
  const [focus, setFocus] = useState("Prevention");
  const [format, setFormat] = useState("Instagram Post");
  const [tone, setTone] = useState("Informative");

  const generate = useServerFn(generateCampaign);
  const mutation = useMutation({
    mutationFn: (vars: {
      audience: string;
      focus: string;
      format: string;
      tone: string;
    }) => generate({ data: vars }),
    onSuccess: () => {
      setTimeout(
        () => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }),
        80,
      );
    },
    onError: (e: Error) => toast.error(e.message ?? "Something went wrong."),
  });

  const handleGenerate = () =>
    mutation.mutate({ audience, focus, format, tone });

  const result = mutation.data as CampaignResult | undefined;

  const asText = (r: CampaignResult) =>
    [
      `BEACON CAMPAIGN`,
      `================`,
      `Title: ${r.title}`,
      ``,
      `Headline: ${r.headline}`,
      ``,
      `Content:`,
      r.content,
      ``,
      `Call to Action: ${r.callToAction}`,
      ``,
      `Suggested Visual Direction:`,
      r.visualDirection,
      ``,
      `Hashtags: ${r.hashtags.map((h) => `#${h.replace(/^#/, "")}`).join(" ")}`,
      ``,
      `Trusted Resources:`,
      ...r.resources.map((s) => `- ${s.name}: ${s.description} (${s.url})`),
      ``,
      `Generated by Beacon. Always review AI-generated content before publication.`,
    ].join("\n");

  const copyContent = async () => {
    if (!result) return;
    await navigator.clipboard.writeText(asText(result));
    toast.success("Campaign copied to clipboard.");
  };

  const downloadTxt = () => {
    if (!result) return;
    const blob = new Blob([asText(result)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `beacon-${result.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen">
      <Toaster position="top-center" richColors />

      {/* Nav */}
      <header className="sticky top-0 z-40 border-b border-border/60 bg-background/70 backdrop-blur-xl">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6">
          <a href="#top" className="flex items-center gap-2">
            <BeaconMark />
            <span className="text-lg font-semibold tracking-tight">Beacon</span>
          </a>
          <nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex">
            <a href="#about" className="hover:text-foreground transition-colors">About</a>
            <a href="#principles" className="hover:text-foreground transition-colors">Principles</a>
            <a href="#faq" className="hover:text-foreground transition-colors">FAQ</a>
          </nav>
          <Button
            size="sm"
            className="rounded-full"
            onClick={() =>
              generatorRef.current?.scrollIntoView({ behavior: "smooth" })
            }
          >
            Get started
          </Button>
        </div>
      </header>

      {/* Hero */}
      <section id="top" className="relative overflow-hidden px-4 pt-16 pb-20 sm:px-6 sm:pt-24 sm:pb-28">
        <div className="mx-auto max-w-4xl text-center animate-fade-up">
          <div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card/70 px-4 py-1.5 text-xs font-medium text-muted-foreground shadow-soft">
            <span className="relative inline-flex h-2 w-2">
              <span className="absolute inline-flex h-full w-full animate-beacon-pulse rounded-full bg-beacon opacity-70" />
              <span className="relative inline-flex h-2 w-2 rounded-full bg-beacon" />
            </span>
            Survivor-centered · Trauma-informed · Responsible AI
          </div>
          <h1 className="text-5xl font-semibold leading-[1.05] tracking-tight sm:text-7xl">
            <span className="gradient-text">Beacon</span>
          </h1>
          <p className="mt-5 text-xl font-medium text-foreground sm:text-2xl">
            AI-powered Ethical Campaign Generator
          </p>
          <p className="mx-auto mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground sm:text-lg">
            Beacon helps advocates, educators, and community organizers create
            trauma-informed awareness campaigns for anti-human trafficking
            initiatives — carefully worded, respectful of survivors, and grounded
            in trusted resources.
          </p>
          <div className="mt-9 flex flex-wrap items-center justify-center gap-3">
            <Button
              size="lg"
              className="rounded-full px-7 shadow-soft"
              onClick={() =>
                generatorRef.current?.scrollIntoView({ behavior: "smooth" })
              }
            >
              Get started
              <ChevronRight className="ml-1 h-4 w-4" />
            </Button>
            <Button
              size="lg"
              variant="ghost"
              className="rounded-full"
              onClick={() =>
                document
                  .getElementById("about")
                  ?.scrollIntoView({ behavior: "smooth" })
              }
            >
              Learn how it works
            </Button>
          </div>
        </div>
      </section>

      {/* Info cards */}
      <section id="about" className="px-4 pb-20 sm:px-6">
        <div className="mx-auto grid max-w-6xl gap-5 sm:grid-cols-2 lg:grid-cols-3">
          <InfoCard
            icon={<HeartHandshake className="h-5 w-5" />}
            title="Why ethical awareness matters"
            body="Awareness campaigns shape public perception. Ethical messaging protects survivors from re-traumatization, avoids stereotypes, and moves audiences toward informed, compassionate action."
            tint="beacon"
          />
          <InfoCard
            icon={<Compass className="h-5 w-5" />}
            title="How Beacon works"
            body="Choose your audience, campaign focus, format, and tone. Beacon drafts a complete, trauma-informed campaign with copy, visual direction, hashtags, and vetted resources."
            tint="sage"
          />
          <InfoCard
            icon={<ShieldCheck className="h-5 w-5" />}
            title="Responsible AI principles"
            body="Beacon follows survivor-centered guidelines: no sensationalism, no graphic imagery, verified resources only, and a reminder that every campaign should be human-reviewed."
            tint="beacon"
          />
        </div>
      </section>

      {/* Generator */}
      <section
        id="generator"
        ref={generatorRef}
        className="scroll-mt-24 px-4 pb-24 sm:px-6"
      >
        <div className="mx-auto max-w-5xl">
          <div className="mb-8 text-center">
            <div className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-medium text-accent-foreground">
              <Sparkles className="h-3.5 w-3.5" />
              Campaign Generator
            </div>
            <h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
              Craft your campaign
            </h2>
            <p className="mx-auto mt-2 max-w-xl text-muted-foreground">
              Tell Beacon a little about your audience and goals. We'll draft a
              respectful, ready-to-review campaign.
            </p>
          </div>

          <div className="card-soft p-6 sm:p-8">
            <div className="grid gap-5 sm:grid-cols-2">
              <Field label="Audience" value={audience} onChange={setAudience} options={AUDIENCES} />
              <Field label="Campaign Focus" value={focus} onChange={setFocus} options={FOCUSES} />
              <Field label="Content Format" value={format} onChange={setFormat} options={FORMATS} />
              <Field label="Tone" value={tone} onChange={setTone} options={TONES} />
            </div>

            <div className="mt-8 flex flex-col items-center gap-3">
              <Button
                size="lg"
                onClick={handleGenerate}
                disabled={mutation.isPending}
                className="rounded-full px-8 shadow-soft"
              >
                {mutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating campaign…
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate Campaign
                  </>
                )}
              </Button>
              <p className="text-xs text-muted-foreground">
                Beacon drafts are a starting point — always review before publishing.
              </p>
            </div>
          </div>

          {/* Loading placeholder */}
          {mutation.isPending && (
            <div className="mt-8 card-soft animate-fade-up p-8">
              <div className="flex items-center gap-3">
                <div className="relative h-3 w-3">
                  <span className="absolute inline-flex h-full w-full animate-beacon-pulse rounded-full bg-beacon opacity-70" />
                  <span className="relative inline-flex h-3 w-3 rounded-full bg-beacon" />
                </div>
                <p className="text-sm text-muted-foreground">
                  Composing a survivor-centered draft…
                </p>
              </div>
              <div className="mt-6 space-y-3">
                <SkeletonBar w="w-1/2" />
                <SkeletonBar w="w-3/4" />
                <SkeletonBar w="w-2/3" />
                <SkeletonBar w="w-5/6" />
              </div>
            </div>
          )}

          {/* Result */}
          {result && !mutation.isPending && (
            <div ref={resultRef} className="mt-10 scroll-mt-24 animate-fade-up">
              <ResultCard
                result={result}
                onCopy={copyContent}
                onDownload={downloadTxt}
                onRegenerate={handleGenerate}
              />
            </div>
          )}
        </div>
      </section>

      {/* About Beacon */}
      <section className="px-4 pb-20 sm:px-6">
        <div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2 lg:items-center">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-medium text-accent-foreground">
              <BookOpen className="h-3.5 w-3.5" />
              About Beacon
            </div>
            <h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
              A quiet, careful tool for loud, urgent work.
            </h2>
            <p className="mt-4 text-muted-foreground leading-relaxed">
              Beacon exists to support the people already doing the hard work of
              trafficking prevention — educators, community leaders, survivors,
              and advocates. It is not a replacement for lived expertise, and it
              is not a substitute for trained professionals. It's a drafting
              partner that prioritizes dignity over drama.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <MiniStat icon={<Users className="h-4 w-4" />} title="Survivor-centered" body="No graphic imagery, no sensationalism, no victim-blaming." />
            <MiniStat icon={<Lightbulb className="h-4 w-4" />} title="Trauma-informed" body="Language reviewed against trauma-informed practice guidelines." />
            <MiniStat icon={<ShieldCheck className="h-4 w-4" />} title="Verified resources" body="Recommends established, trusted anti-trafficking organizations." />
            <MiniStat icon={<Sparkles className="h-4 w-4" />} title="Human-in-the-loop" body="Every draft is a starting point, never a final publication." />
          </div>
        </div>
      </section>

      {/* Ethical AI Statement */}
      <section id="principles" className="px-4 pb-20 sm:px-6">
        <div className="mx-auto max-w-4xl card-soft p-8 sm:p-10">
          <div className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-medium text-accent-foreground">
            <ShieldCheck className="h-3.5 w-3.5" />
            Ethical AI Statement
          </div>
          <h2 className="mt-4 text-3xl font-semibold tracking-tight">
            Our commitments
          </h2>
          <ul className="mt-6 space-y-4 text-muted-foreground">
            <Commitment title="Dignity first">
              Content centers the humanity and agency of people impacted by trafficking. We refuse framings that reduce anyone to a victim narrative.
            </Commitment>
            <Commitment title="Accuracy over urgency">
              Beacon prefers verified information and established resources over dramatic statistics or scare tactics.
            </Commitment>
            <Commitment title="Human oversight">
              AI drafts are not published automatically. Every campaign should be reviewed by people with relevant expertise and, where possible, lived experience.
            </Commitment>
            <Commitment title="No exploitation">
              Beacon does not generate graphic descriptions, identifying details, or imagery that could re-traumatize survivors or endanger anyone at risk.
            </Commitment>
          </ul>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="px-4 pb-24 sm:px-6">
        <div className="mx-auto max-w-3xl">
          <div className="mb-8 text-center">
            <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
              Frequently asked
            </h2>
          </div>
          <div className="card-soft p-2 sm:p-4">
            <Accordion type="single" collapsible className="w-full">
              <Faq q="Is Beacon a replacement for expert-led campaigns?">
                No. Beacon is a drafting tool. Campaigns should always be reviewed by
                people with subject-matter expertise, ideally including survivors and
                trained anti-trafficking professionals.
              </Faq>
              <Faq q="How does Beacon avoid harmful stereotypes?">
                Beacon is instructed to avoid sensationalism, graphic imagery,
                victim-blaming, and demographic stereotypes. It focuses on prevention,
                education, and community action.
              </Faq>
              <Faq q="Where do the recommended resources come from?">
                Beacon recommends established organizations such as the National
                Human Trafficking Hotline, Polaris Project, DHS Blue Campaign,
                Thorn, and ECPAT. Always confirm resources are current before publishing.
              </Faq>
              <Faq q="Can I use Beacon campaigns commercially?">
                Beacon output is a draft you own and are responsible for. Review
                carefully, adapt to your context, and follow the guidelines of any
                organization or platform you publish through.
              </Faq>
              <Faq q="What if I need to report trafficking right now?">
                In the U.S., call the National Human Trafficking Hotline at
                1-888-373-7888, text 233733, or visit humantraffickinghotline.org.
                In an emergency, call your local emergency number.
              </Faq>
            </Accordion>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/60 bg-card/40 px-4 py-10 sm:px-6">
        <div className="mx-auto max-w-6xl">
          <div className="flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center">
            <div className="flex items-center gap-2">
              <BeaconMark />
              <span className="text-sm font-semibold">Beacon</span>
            </div>
            <p className="text-xs text-muted-foreground sm:text-right sm:max-w-md">
              Disclaimer: Beacon uses AI to draft awareness content. All
              AI-generated campaigns should be carefully reviewed — and, where
              possible, reviewed by people with lived experience or professional
              expertise — before publication or distribution.
            </p>
          </div>
          <div className="mt-6 text-xs text-muted-foreground">
            © {new Date().getFullYear()} Beacon. Made in service of survivor-centered advocacy.
          </div>
        </div>
      </footer>
    </div>
  );
}

/* ---------- Subcomponents ---------- */

function BeaconMark() {
  return (
    <span className="relative inline-flex h-8 w-8 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-beacon shadow-soft">
      <span className="absolute inset-0 rounded-2xl bg-beacon/40 blur-md" aria-hidden />
      <span className="relative h-2.5 w-2.5 rounded-full bg-primary-foreground" />
    </span>
  );
}

function Field({
  label,
  value,
  onChange,
  options,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: string[];
}) {
  return (
    <div className="space-y-2">
      <Label className="text-sm font-medium text-foreground">{label}</Label>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger className="h-11 rounded-xl">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {options.map((o) => (
            <SelectItem key={o} value={o}>
              {o}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  );
}

function InfoCard({
  icon,
  title,
  body,
  tint,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
  tint: "beacon" | "sage";
}) {
  return (
    <div className="card-soft card-soft-hover p-6">
      <div
        className={`inline-flex h-10 w-10 items-center justify-center rounded-xl ${
          tint === "beacon"
            ? "bg-beacon/10 text-beacon"
            : "bg-sage/15 text-sage-foreground"
        }`}
      >
        {icon}
      </div>
      <h3 className="mt-4 text-lg font-semibold tracking-tight">{title}</h3>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
    </div>
  );
}

function SkeletonBar({ w }: { w: string }) {
  return (
    <div className={`h-3 ${w} animate-pulse rounded-full bg-muted`} />
  );
}

function MiniStat({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <div className="card-soft p-5">
      <div className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-accent text-accent-foreground">
        {icon}
      </div>
      <p className="mt-3 font-semibold text-foreground">{title}</p>
      <p className="mt-1 text-sm text-muted-foreground">{body}</p>
    </div>
  );
}

function Commitment({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <li className="flex gap-3">
      <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-beacon" />
      <div>
        <p className="font-semibold text-foreground">{title}</p>
        <p className="text-sm leading-relaxed">{children}</p>
      </div>
    </li>
  );
}

function Faq({ q, children }: { q: string; children: React.ReactNode }) {
  return (
    <AccordionItem value={q} className="border-b last:border-b-0">
      <AccordionTrigger className="px-3 text-left text-base font-medium hover:no-underline">
        {q}
      </AccordionTrigger>
      <AccordionContent className="px-3 text-muted-foreground">
        {children}
      </AccordionContent>
    </AccordionItem>
  );
}

function ResultCard({
  result,
  onCopy,
  onDownload,
  onRegenerate,
}: {
  result: CampaignResult;
  onCopy: () => void;
  onDownload: () => void;
  onRegenerate: () => void;
}) {
  return (
    <div className="card-soft overflow-hidden">
      <div className="bg-gradient-to-br from-primary to-beacon px-6 py-8 text-primary-foreground sm:px-10 sm:py-10">
        <p className="text-xs font-medium uppercase tracking-widest opacity-80">
          Campaign draft
        </p>
        <h3 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">
          {result.title}
        </h3>
        <p className="mt-3 max-w-2xl text-lg opacity-95">{result.headline}</p>
      </div>

      <div className="space-y-8 p-6 sm:p-10">
        <Section title="Main content">
          <p className="whitespace-pre-line leading-relaxed text-foreground/90">
            {result.content}
          </p>
        </Section>

        <Section title="Call to action">
          <div className="rounded-xl border border-border bg-accent/50 p-4 font-medium text-accent-foreground">
            {result.callToAction}
          </div>
        </Section>

        <Section title="Suggested visual direction">
          <p className="leading-relaxed text-muted-foreground">
            {result.visualDirection}
          </p>
        </Section>

        <Section title="Recommended hashtags">
          <div className="flex flex-wrap gap-2">
            {result.hashtags.map((h) => (
              <span
                key={h}
                className="rounded-full bg-sage/15 px-3 py-1 text-sm font-medium text-sage-foreground"
              >
                #{h.replace(/^#/, "")}
              </span>
            ))}
          </div>
        </Section>

        <Section title="Trusted resources">
          <ul className="grid gap-3 sm:grid-cols-2">
            {result.resources.map((r) => (
              <li key={r.name} className="rounded-xl border border-border p-4">
                <a
                  href={r.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-semibold text-primary hover:underline"
                >
                  {r.name}
                </a>
                <p className="mt-1 text-sm text-muted-foreground">
                  {r.description}
                </p>
              </li>
            ))}
          </ul>
        </Section>

        <div className="flex flex-wrap gap-3 border-t border-border pt-6">
          <Button onClick={onCopy} variant="secondary" className="rounded-full">
            <Copy className="mr-2 h-4 w-4" /> Copy Content
          </Button>
          <Button onClick={onDownload} variant="secondary" className="rounded-full">
            <Download className="mr-2 h-4 w-4" /> Download as TXT
          </Button>
          <Button onClick={onRegenerate} className="rounded-full">
            <RefreshCw className="mr-2 h-4 w-4" /> Generate Another Version
          </Button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
        {title}
      </p>
      <div className="mt-2">{children}</div>
    </div>
  );
}
